# Generated by Django 4.0.3 on 2022-03-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacam',
            name='Id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
